<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cardholders List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            width: 80%;
            max-width: 1000px;
            background-color: #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 20px;
            border-radius: 10px;
        }
        h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #dddddd;
        }
        th, td {
            padding: 12px 15px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
        .inhouse-yes {
            color: green;
            font-weight: bold;
        }
        .inhouse-no {
            color: red;
            font-weight: bold;
        }
        .n-a {
            color: gray;
        }
        .timestamp {
            color: #555;
            font-size: 0.9em;
        }
    </style>
    <script>
        // Function to fetch data from the server and update the table
        function fetchCardholders() {
            var xhr = new XMLHttpRequest();
            xhr.open('GET', 'fetch_cardholders.php', true); // Call the PHP endpoint
            
            xhr.onload = function() {
                if (this.status === 200) {
                    var cardholders = JSON.parse(this.responseText);
                    var tableBody = document.querySelector('tbody');
                    tableBody.innerHTML = ''; // Clear existing rows

                    // Loop through each cardholder and add rows dynamically
                    cardholders.forEach(function(cardholder) {
                        var row = document.createElement('tr');
                        
                        row.innerHTML = `
                            <td>${cardholder.cardId}</td>
                            <td>${cardholder.name}</td>
                            <td>${cardholder.email}</td>
                            <td class="${cardholder.inhouse === 'yes' ? 'inhouse-yes' : (cardholder.inhouse === 'no' ? 'inhouse-no' : 'n-a')}">
                                ${cardholder.inhouse || 'N/A'}
                            </td>
                            <td class="timestamp">${cardholder.timestamp || 'N/A'}</td>
                        `;
                        
                        tableBody.appendChild(row);
                    });
                }
            };
            
            xhr.send();
        }

        // Automatically fetch and update the table every 10 seconds
        setInterval(fetchCardholders, 10000); // 10000ms = 10 seconds

        // Fetch cardholders data when the page first loads
        window.onload = fetchCardholders;
    </script>
</head>
<body>
    <div class="container">
        <h1>Cardholders List</h1>
        <table>
            <thead>
                <tr>
                    <th>Card ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>In-House</th>
                    <th>Last Timestamp</th>
                </tr>
            </thead>
            <tbody>
                <!-- Table rows will be dynamically generated by JavaScript -->
            </tbody>
        </table>
    </div>
</body>
</html>
